### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by sankhesh**

### CODE REVIEW

**Comment by sankhesh** [comment]
Testing

**Comment by sankhesh** [comment]
One more test comment

**Comment by sankhesh** [comment]
Do: check

**Comment by sankhesh** [comment]
Do: merge

**Comment by sankhesh** [comment]
Do: test

**Comment by sankhesh** [comment]
Do: test

**Comment by sankhesh** [comment]
Do: test

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
*Warning*: The merge request is marked as a Work in Progress.  
**SERVER ERROR**: project TestGithubAPI directory not available! @sankhesh

**Comment by kwrobot01** [comment]
*Warning*: The merge request is marked as a Work in Progress.  
**SERVER ERROR**: project TestGithubAPI directory not available! @sankhesh

**Comment by kwrobot01** [comment]
*Warning*: The merge request is marked as a Work in Progress.  
**SERVER ERROR**: project TestGithubAPI directory not available! @sankhesh

**Comment by kwrobot01** [comment]
Testing

**Comment by kwrobot01** [comment]
Do: test

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
Testing

**Comment by kwrobot01** [comment]
Testing

**Comment by kwrobot01** [comment]
*Warning*: The merge request is marked as a Work in Progress.  
**SERVER ERROR**: project TestGithubAPI directory not available! @sankhesh

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
*Warning*: The merge request is marked as a Work in Progress.  
**SERVER ERROR**: project TestGithubAPI directory not available! @sankhesh

**Comment by kwrobot01** [comment]
*Warning*: The merge request is marked as a Work in Progress.  
**SERVER ERROR**: project TestGithubAPI directory not available! @sankhesh

**Comment by kwrobot01** [comment]
*Warning*: The merge request is marked as a Work in Progress.  
**SERVER ERROR**: project TestGithubAPI directory not available! @sankhesh

**Comment by kwrobot01** [comment]
*Warning*: The merge request is marked as a Work in Progress.  
**SERVER ERROR**: project TestGithubAPI directory not available! @sankhesh

**Comment by kwrobot01** [comment]
*Warning*: The merge request is marked as a Work in Progress.  
Basic content checks failed!

```
**SERVER ERROR**: hook for TestGithubAPI not available! @sankhesh
```

Branch-at: 46a7c70564ea7a98d2ce8aba3a825fb4cc1a40b9  
Rejected-by: @kwrobot01

**Comment by sankhesh** [comment]
Test comment

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
*Warning*: The merge request is marked as a Work in Progress.  
**SERVER ERROR**: project TestGithubAPI directory not available! @sankhesh

**Comment by kwrobot01** [comment]
*Warning*: The merge request is marked as a Work in Progress.  
**SERVER ERROR**: project TestGithubAPI directory not available! @sankhesh

**Comment by kwrobot01** [comment]
*Warning*: The merge request is marked as a Work in Progress.  
**SERVER ERROR**: project TestGithubAPI directory not available! @sankhesh

**Comment by kwrobot01** [comment]
*Warning*: The merge request is marked as a Work in Progress.  
Basic content checks failed!

```
Traceback (most recent call last):
  File "/Users/sankheshjhaveri/Projects/GitRobot/hookroot/TestGithubAPI/update.py", line 1, in <module>
    import githooks
ImportError: No module named githooks
Traceback (most recent call last):
  File "/Users/sankheshjhaveri/Projects/GitRobot/hookroot/TestGithubAPI/update.py", line 1, in <module>
    import githooks
ImportError: No module named githooks
Traceback (most recent call last):
  File "/Users/sankheshjhaveri/Projects/GitRobot/hookroot/TestGithubAPI/update.py", line 1, in <module>
    import githooks
ImportError: No module named githooks
```

Branch-at: 46a7c70564ea7a98d2ce8aba3a825fb4cc1a40b9  
Rejected-by: @kwrobot01

**Comment by kwrobot01** [comment]
*Warning*: The merge request is marked as a Work in Progress.  
Basic content checks failed!

```
Traceback (most recent call last):
  File "/Users/sankheshjhaveri/Projects/GitRobot/hookroot/TestGithubAPI/update.py", line 1, in <module>
    import githooks
  File "/Users/sankheshjhaveri/Projects/GitRobot/githooks/__init__.py", line 26, in <module>
    from CheckPerson import CheckPerson
  File "/Users/sankheshjhaveri/Projects/GitRobot/githooks/CheckPerson.py", line 17, in <module>
    import dns.resolver
ImportError: No module named dns.resolver
Traceback (most recent call last):
  File "/Users/sankheshjhaveri/Projects/GitRobot/hookroot/TestGithubAPI/update.py", line 1, in <module>
    import githooks
  File "/Users/sankheshjhaveri/Projects/GitRobot/githooks/__init__.py", line 26, in <module>
    from CheckPerson import CheckPerson
  File "/Users/sankheshjhaveri/Projects/GitRobot/githooks/CheckPerson.py", line 17, in <module>
    import dns.resolver
ImportError: No module named dns.resolver
Traceback (most recent call last):
  File "/Users/sankheshjhaveri/Projects/GitRobot/hookroot/TestGithubAPI/update.py", line 1, in <module>
    import githooks
  File "/Users/sankheshjhaveri/Projects/GitRobot/githooks/__init__.py", line 26, in <module>
    from CheckPerson import CheckPerson
  File "/Users/sankheshjhaveri/Projects/GitRobot/githooks/CheckPerson.py", line 17, in <module>
    import dns.resolver
ImportError: No module named dns.resolver
```

Branch-at: 46a7c70564ea7a98d2ce8aba3a825fb4cc1a40b9  
Rejected-by: @kwrobot01

**Comment by kwrobot01** [comment]
*Warning*: The merge request is marked as a Work in Progress.  
Basic content checks failed!

```
Traceback (most recent call last):
  File "/Users/sankheshjhaveri/Projects/GitRobot/hookroot/TestGithubAPI/update.py", line 32, in <module>
    ('7.0.x', '7031b5a81b0fa9a238a7f84c8c28ff0c151cd9e1'),
  File "/Users/sankheshjhaveri/Projects/GitRobot/githooks/Update.py", line 168, in check_for_release_branches
    base = git('merge-base', non_release_root, self.newrev)
  File "/Users/sankheshjhaveri/Projects/GitRobot/githooks/Utility.py", line 50, in git
    if p.returncode != 0: raise GitError(result[1])
githooks.Git.GitError: 'fatal: Not a valid commit name 1ec1fd0226c3259b7494e5c2dba4cf310fde9b4d\n'
```

Branch-at: 46a7c70564ea7a98d2ce8aba3a825fb4cc1a40b9  
Rejected-by: @kwrobot01

**Comment by kwrobot01** [comment]
*Warning*: The merge request is marked as a Work in Progress.  
Basic content checks passed!

Branch-at: 46a7c70564ea7a98d2ce8aba3a825fb4cc1a40b9  
Acked-by: @kwrobot01

**Comment by sankhesh** [comment]
Do: test

**Comment by kwrobot01** [comment]
*Warning*: The merge request is marked as a Work in Progress.  
Testing commands handed to buildbot.

Branch-at: 46a7c70564ea7a98d2ce8aba3a825fb4cc1a40b9

**Comment by sankhesh** [comment]
Do: merge

**Comment by kwrobot01** [comment]
**SERVER ERROR**: exception while creating the commit! @sankhesh

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: 46a7c70564ea7a98d2ce8aba3a825fb4cc1a40b9

**Comment by kwrobot01** [comment]
Testing commands handed to buildbot.

Branch-at: 46a7c70564ea7a98d2ce8aba3a825fb4cc1a40b9

**Comment by sankhesh** [comment]
Do: test

**Comment by sankhesh** [comment]
Do: merge

**Comment by kwrobot01** [comment]
**SERVER ERROR**: exception while creating the commit! @sankhesh

**Comment by sankhesh** [comment]
Do: merge

**Comment by kwrobot01** [comment]
**SERVER ERROR**: exception while creating the commit! @sankhesh

**Comment by sankhesh** [comment]
Do: merge

**Comment by kwrobot01** [comment]
Automatic merge failed!

Basic content checks on the merge commit failed!

```
commit 45c5352f has unknown author domain "".  Run
  git config --global user.name 'Your Name'
  git config --global user.email 'you@yourdomain.com'
before creating commits.

```

**Comment by sankhesh** [comment]
Do: merge

**Comment by kwrobot01** [comment]
Automatic merge failed!

Basic content checks on the merge commit failed!

```
commit b73ec2fb has unknown author domain "".  Run
  git config --global user.name 'Your Name'
  git config --global user.email 'you@yourdomain.com'
before creating commits.

```

**Comment by kwrobot01** [comment]
Automatic merge failed!

Basic content checks on the merge commit failed!

```
commit 23646980 has unknown author domain "".  Run
  git config --global user.name 'Your Name'
  git config --global user.email 'you@yourdomain.com'
before creating commits.

```

**Comment by sankhesh** [comment]
Do: merge

**Comment by kwrobot01** [comment]
Automatic merge failed!

Basic content checks on the merge commit failed!

```
commit 8bae8a56 has unknown author domain "".  Run
  git config --global user.name 'Your Name'
  git config --global user.email 'you@yourdomain.com'
before creating commits.

```

**Comment by sankhesh** [comment]
Do: merge

**Comment by kwrobot01** [comment]
Automatic merge failed!

Basic content checks on the merge commit failed!

```
commit 55718a8c has unknown author domain "".  Run
  git config --global user.name 'Your Name'
  git config --global user.email 'you@yourdomain.com'
before creating commits.

```

**Comment by sankhesh** [comment]
Do: merge

**Comment by kwrobot01** [comment]
Automatic merge failed!

Basic content checks on the merge commit failed!

```
commit 67527fad has unknown author domain "".  Run
  git config --global user.name 'Your Name'
  git config --global user.email 'you@yourdomain.com'
before creating commits.

```

**Comment by sankhesh** [comment]
Do: merge

**Comment by kwrobot01** [comment]
Automatic merge failed!

Basic content checks on the merge commit failed!

```
commit c8bf3ac2 has unknown author domain "".  Run
  git config --global user.name 'Your Name'
  git config --global user.email 'you@yourdomain.com'
before creating commits.

```

**Comment by sankhesh** [comment]
Do: merge

**Comment by kwrobot01** [comment]
Automatic merge failed!

Basic content checks on the merge commit failed!

```
commit 4a7a2967 has unknown author domain "".  Run
  git config --global user.name 'Your Name'
  git config --global user.email 'you@yourdomain.com'
before creating commits.

```

**Comment by kwrobot01** [comment]
Automatic merge failed!

Basic content checks on the merge commit failed!

```
commit 57b8791d has unknown author domain "".  Run
  git config --global user.name 'Your Name'
  git config --global user.email 'you@yourdomain.com'
before creating commits.

```

**Comment by sankhesh** [comment]
Do: merge

**Comment by kwrobot01** [comment]
Automatic merge failed!

Basic content checks on the merge commit failed!

```
commit 4d15dbcb has unknown author domain "".  Run
  git config --global user.name 'Your Name'
  git config --global user.email 'you@yourdomain.com'
before creating commits.

```

**Comment by kwrobot01** [comment]
Automatic merge failed!

Basic content checks on the merge commit failed!

```
commit 4f2399e1 has unknown author domain "".  Run
  git config --global user.name 'Your Name'
  git config --global user.email 'you@yourdomain.com'
before creating commits.

```

**Comment by sankhesh** [comment]
Do: merge

**Comment by kwrobot01** [comment]
Automatic merge failed!

Basic content checks on the merge commit failed!

```
commit d2978e8c has author name "None" with no space.  Run
  git config --global user.name 'Your Name'
  git config --global user.email 'you@yourdomain.com'
before creating commits.

```

**Comment by sankhesh** [comment]
Do: merge

**Comment by kwrobot01** [comment]
Automatic merge failed!

Basic content checks on the merge commit failed!

```
commit 2ac760fb has author name "None" with no space.  Run
  git config --global user.name 'Your Name'
  git config --global user.email 'you@yourdomain.com'
before creating commits.

```

**Comment by sankhesh** [comment]
Do: merge

**Comment by kwrobot01** [comment]
Automatic merge failed!

*Warning*: Merge requester @sankhesh cannot be author of merge commit since his/her email is not publicly visible.

Making @kwrobot01 the merge authorBasic content checks on the merge commit failed!

```
commit a3547e7a has author name "None" with no space.  Run
  git config --global user.name 'Your Name'
  git config --global user.email 'you@yourdomain.com'
before creating commits.

```

**Comment by sankhesh** [comment]
Do: merge

**Pull request merged**
