### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by sankhesh**

### CODE REVIEW

**Comment by kwrobot01** [comment]
Basic content checks failed!

```
commit 25bd8e2f has committer name "GitHub" with no space.  Run
  git config --global user.name 'Your Name'
  git config --global user.email 'you@yourdomain.com'
before creating commits.
```

Branch-at: 25bd8e2f634ea59421a3d8f37f3bf05860bd3621  
Rejected-by: @kwrobot01

**Comment by kwrobot01** [comment]
Basic content checks failed!

```
commit 25bd8e2f has committer name "GitHub" with no space.  Run
  git config --global user.name 'Your Name'
  git config --global user.email 'you@yourdomain.com'
before creating commits.
```

Branch-at: 25bd8e2f634ea59421a3d8f37f3bf05860bd3621  
Rejected-by: @kwrobot01

**Comment by sankhesh** [comment]
Do: test

**Comment by sankhesh** [comment]
Do: merge

**Pull request merged**
